"""
Django settings for stackproj project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""
# import ipdb;ipdb.set_trace()
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os



import djcelery
djcelery.setup_loader()

# #Broker settings
# BROKER_HOST ="localhost"
# BROKER_PORT = 5672
# BROKER_USER ="guest"
# BROKER_PASSWORD = "guest"
# BROKER_VHOST = "/"
# CELERY_ALWAYS_EAGER = False
BROKER_BACKEND = "django"
# CELERY_ACCEPT_CONTENT = ['json']
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'l0^@t_!sdjhy$zuhbksiqtlxs=eg$gfhvjki#2fmtjziwa10p6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework.authtoken',
    'accounts',
    'stackapp',
    'core',
    'rest_framework',
    'rest_framework_swagger',
    'djcelery',
    'kombu.transport.django',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'stackproj.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stackproj.wsgi.application'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
        
  
}

#sqlite databse
# 'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
# ##


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
# 'ENGINE': 'django.db.backends.sqlite3',
# 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'stack1',
        'USER': 'stack1user',
        'PASSWORD': 'test1234',
        'HOST': 'localhost',
        'PORT': '',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True



# swagger settings

# SWAGGER_SETTINGS = {
#     "exclude_namespaces": [],  # List URL namespaces to ignore
#     "api_version": '0.6',  # Specify your API's version
#     "api_path": "/",  # Specify the path to your API not a root level
#     "enabled_methods": [  # Specify which methods to enable in Swagger UI
#         'get',
#         'post',
#         'put',
#         'patch',
#         'delete'
#     ],
#     "api_key": '',  # An API key
#     "is_authenticated": False,  # Set to True to enforce user authentication,
#     "is_superuser": False,  # Set to True to enforce admin only access0
# }


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
PROTOCOL = 'http'

EMAIL_HOST = 'localhost'
EMAIL_PORT = 25


# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_HOST_USER = 'testmail0887@gmail.com'
# EMAIL_HOST_PASSWORD = 'kr!sh123'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True

COMM_EMAIL_SENDER = 'testmail0887@gmail.com'
MAX_UPLOAD_SIZE = 5242880

